### ISSUE TITLE
Utils: Write test for AddressUtils library

### ISSUE THREAD

**Issue by nivida** [aragon/govern#114]

**Comment by onbjerg** [comment]
It seems that both methods in the library do the exact same thing, and that `toAddress` is currently unused. Is this the intention? :thinking: 

Also, as far as I know the difference between `address` and `address payable` is only visible at compile-time, so I'm not entirely sure about the testing strategy.

**Comment by izqui** [comment]
Yeah, I am not entirely sure. I added both even though we only needed one of them. I think testing the conversion from a mock contract should be enough, a good testing strategy could even be start with one type of address, apply both conversions at the contract side and assert that we end with the same address
