### ISSUE TITLE
CI/CD: Govern Server E2E test randomly fails

### ISSUE THREAD

**Issue by nivida** [aragon/govern#182]
- E2E test run should explicit wait until the server is actually running (flickering behavior currently in the CD run)

**Comment by promaty** [comment]
@nivida I think I fixed it in this #154.
We will do another run after #190 shouldn't be any issues

**Comment by promaty** [comment]
@nivida Seems to deploy fine now, feel free to close: https://github.com/aragon/govern/actions/runs/349978729
