### ISSUE TITLE
CI/CD: fix hardhat ignoring contract cache

### ISSUE THREAD

**Issue by promaty** [aragon/govern#186]
As you can see in this CI/CD run: https://github.com/aragon/govern/runs/1352916827?check_suite_focus=true
`govern-contract-utils` ignores all locally cached artifacts when running `hardhat compile`
The following directories are available before the run:
- `~/.cache/hardhat-nodejs/compilers/linux-amd64/`
- `packages/govern-contract-utils/contracts`
- `packages/govern-contract-utils/cache`

This is not an issue with `buidler`, which outputs `All contracts have already been compiled, skipping compilation.`
Running `hardhat` multiple times locally outputs `Nothing to compile`, but it doesn't seem to work in CI/CD runs.

**Comment by Evalir** [comment]
Can't we force recompilation with `hardhat compile --force`?

**Comment by promaty** [comment]
@Evalir that works fine but we don't take advantage of the cache and it takes longer.
If I remove `--force` it should use the cache, but it behaves as if I still have `--force`
See #188

**Comment by alcuadrado** [comment]
Hey @promaty, I believe the issue here comes from hardhat comparing the modification date of your source files, which actually changes due to the CI cache. We'll get into this.

/cc @fvictorio

**Comment by alcuadrado** [comment]
@promaty we just released [Hardhat v2.0.4](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.0.4), which should fix this. The cache system doesn't use FS timestamps anymore, but content hashes.

**Comment by promaty** [comment]
@alcuadrado Confirmed it works, thanks! https://github.com/aragon/govern/runs/1465767029
```
@aragon/govern-contract-utils: $ yarn hardhat compile
@aragon/govern-contract-utils: $ /home/runner/work/govern/govern/node_modules/.bin/hardhat compile
@aragon/govern-contract-utils: Nothing to compile
```

**Comment by fvictorio** [comment]
Awesome!

Just a comment, I think you should include the `hardhat.config.js` file in the cache key:

https://github.com/aragon/govern/blob/a0ce022eb1a6c8ad991bd44cc9a0cc47865a342b/.github/workflows/contracts-ci-cd.yml#L29

Otherwise, the cache won't be evicted if you change your compilers settings.

**Comment by promaty** [comment]
Good catch, will update

**Comment by promaty** [comment]
Actually hardhat seems smart enough to ignore cache if I change anything in `HardhatUserConfig` so it's fine for now

**Comment by fvictorio** [comment]
Ok, yeah, it will ignore the cache if you change a compiler setting. Just keep this in mind if you override a task or install a plugin that does something during the compilation pipeline, because in that case it could give you a false negative :slightly_smiling_face:
