### ISSUE TITLE
Add data structures + contract types to ERC3K.js

### ISSUE THREAD

**Issue by Evalir** [aragon/govern#37]
We should add the main data structures / contract types of Govern to ERC3K.js, so we can easily both receive and send actions, containers, collaterals, and so on.

**Comment by Evalir** [comment]
Re-assigned this task; I'll be working on the console and probably the discord bot through the week, so it might make sense for the API / DX team to get on this task.

**Comment by nivida** [comment]
As discussed are we able to close this issue. The structure of the project changed and the ``erc3k.js`` lib is no longer required. Those functionalities will be moved out to a ``core`` package from the ``govern-server`` package. 

@bpierre Feel free to elaborate on our decision further here.

**Comment by bpierre** [comment]
Yes let’s close it since it was about ERC3K.js as a prototype.

**Comment by nivida** [comment]
New Issue: #61
