### ISSUE TITLE
Govern.js

### ISSUE THREAD

**Issue by bpierre** [aragon/govern#75]
- JS library (browser + node) fetching data from a Govern Server, through its GraphQL API.
- Reflects the [Govern Server JS API](https://github.com/aragon/govern/blob/a14370b6bd248ecd3b956815113dd980c1391484/packages/govern-server/src/core/data/index.ts#L76-L131). 
- Inspired by the [Connect](https://connect.aragon.org/) API.
- Actions resulting in transactions can go through a local Ethereum provider or the Govern Server.

Should we use `@aragon/govern.js` as a package name? @izqui 

Implementation: https://github.com/aragon/govern/pull/77

**Comment by izqui** [comment]
Name sounds good to me. We will prob want to then package some of these things together under the Aragon Connect 2 umbrella, but that’s pure marketing cc @luisivan @ganeJackS
