### ISSUE TITLE
Utils: Rename events to "Lock" and "Unlock", accept ETH deposits

### ISSUE THREAD

**Issue by Evalir** [aragon/govern#95]
See [this note](https://github.com/aragon/govern/pull/43/files#diff-79272041a662f4d06efa8b654818813f10dbd0bca4d56c909422b4f484d7e9a6R14).

**Comment by izqui** [comment]
Initially I added support for ETH collateral deposits, but then ended up removing it in favor of just using WETH when ETH is needed.
